openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
paths:
  /products:
    get:
      summary: Search products
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/q'
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                multiple:
                  summary: Multiple products
                  value:
                    - name: "Fraise"
                      expiration_datetime: "2025-12-31T23:59:59Z"
                      price: 1.99
                    - name: "Jus"
                      expiration_datetime: "2025-11-15T23:59:59Z"
                      price: 0.99
                empty:
                  summary: Empty list
                  value: []
components:
  parameters:
    limit:
      name: limit
      in: query
      schema:
        type: integer
      required: false
    q:
      name: q
      in: query
      schema:
        type: string
      required: false
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
